#!/usr/bin/env python3
"""Generate Lighthouse themes from themes/*.toml.

For each theme this checks WCAG contrast, then writes into rootfs/:
  usr/share/lighthouse/themes/<id>/  theme.json, palette.json, niri.kdl,
                                     noctalia.toml, wallpaper.svg
  etc/lighthouse/noctalia/palettes/<id>.json   (Noctalia only reads palettes here)
and installs DEFAULT_THEME as the current theme (what `lighthouse-theme set` does).

  scripts/gen-themes.py           regenerate
  scripts/gen-themes.py --check   fail if contrast is too low or output is stale
"""

import json
import math
import random
import shutil
import sys
import tempfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_THEME = "christopher-robin"

# (foreground, background, minimum ratio, why)
CONTRAST_RULES = [
    ("on_surface", "surface", 7.0, "body text (WCAG AAA)"),
    ("on_surface_variant", "surface_variant", 4.5, "secondary text (AA)"),
    ("on_primary", "primary", 4.5, "text on primary buttons (AA)"),
    ("on_secondary", "secondary", 4.5, "text on secondary (AA)"),
    ("on_tertiary", "tertiary", 4.5, "text on tertiary (AA)"),
    ("on_error", "error", 4.5, "text on errors (AA)"),
    ("primary", "surface", 3.0, "focus ring and icons vs background (1.4.11)"),
    ("outline", "surface", 3.0, "borders vs background (1.4.11)"),
]


# --- colour helpers ----------------------------------------------------------

def rgb(hex_):
    h = hex_.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def hexc(c):
    return "#%02X%02X%02X" % tuple(max(0, min(255, round(v))) for v in c)


def mix(a, b, t):
    return hexc(tuple(x + (y - x) * t for x, y in zip(rgb(a), rgb(b))))


def luminance(hex_):
    def chan(v):
        v /= 255
        return v / 12.92 if v <= 0.03928 else ((v + 0.055) / 1.055) ** 2.4
    r, g, b = (chan(v) for v in rgb(hex_))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a, b):
    la, lb = sorted((luminance(a), luminance(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def contrast_problems(theme):
    c = theme["colors"]
    return [f"{fg} on {bg}: {contrast(c[fg], c[bg]):.2f} < {need} ({why})"
            for fg, bg, need, why in CONTRAST_RULES if contrast(c[fg], c[bg]) < need]


# --- outputs -------------------------------------------------------------------

def noctalia_palette(theme):
    c = theme["colors"]
    dark = theme["mode"] == "dark"
    variant = {
        "mPrimary": c["primary"], "mOnPrimary": c["on_primary"],
        "mSecondary": c["secondary"], "mOnSecondary": c["on_secondary"],
        "mTertiary": c["tertiary"], "mOnTertiary": c["on_tertiary"],
        "mError": c["error"], "mOnError": c["on_error"],
        "mSurface": c["surface"], "mOnSurface": c["on_surface"],
        "mSurfaceVariant": c["surface_variant"], "mOnSurfaceVariant": c["on_surface_variant"],
        "mOutline": c["outline"],
        "mShadow": "#000000" if dark else mix(c["surface"], "#000000", 0.25),
        "mHover": mix(c["surface_variant"], c["primary"], 0.18),
        "mOnHover": c["on_surface"],
    }
    # Each theme is one mode; give Noctalia the same colours for both variants.
    return {"dark": variant, "light": variant}


def niri_kdl(theme):
    c = theme["colors"]
    return f"""// Generated by scripts/gen-themes.py from themes/{theme['id']}.toml
layout {{
    focus-ring {{
        active-color "{c['primary']}"
        inactive-color "{c['outline']}"
    }}
}}
"""


def noctalia_toml(theme):
    return f"""# Generated by scripts/gen-themes.py from themes/{theme['id']}.toml
[theme]
mode           = "{theme['mode']}"
source         = "custom"
custom_palette = "{theme['id']}"

[wallpaper.default]
path = "/usr/share/lighthouse/themes/{theme['id']}/wallpaper.svg"
"""


def theme_json(theme):
    return {k: theme[k] for k in ("id", "name", "mode", "description")} | {"colors": theme["colors"]}


# --- wallpapers ----------------------------------------------------------------
# Original scenes inspired by the settings of A. A. Milne's books (1926/1928).
# Drawn from simple shapes; no character likenesses.

W, H = 1920, 1080


def hill(y, amp, waves, phase, color, opacity=1):
    pts = [f"{x},{y + amp * math.sin(x / W * waves * 2 * math.pi + phase):.1f}"
           for x in range(0, W + 40, 40)]
    return f'<path d="M0,{H} L{" L".join(pts)} L{W},{H} Z" fill="{color}" opacity="{opacity}"/>'


def ground_y(y, amp, waves, phase, x):
    return y + amp * math.sin(x / W * waves * 2 * math.pi + phase)


def cloud(x, y, s, color, opacity=0.9):
    puffs = [(0, 0, 60), (55, -25, 50), (110, 0, 55), (55, 15, 55), (-45, 12, 40), (155, 15, 38)]
    circles = "".join(f'<circle cx="{x + dx * s:.0f}" cy="{y + dy * s:.0f}" r="{r * s:.0f}"/>'
                      for dx, dy, r in puffs)
    return f'<g fill="{color}" opacity="{opacity}">{circles}</g>'


def stars(n, seed, color, y_max=700, r_max=3.2):
    rnd = random.Random(seed)
    out = []
    for _ in range(n):
        x, y, r = rnd.uniform(0, W), rnd.uniform(70, y_max), rnd.uniform(1.2, r_max)
        out.append(f'<circle cx="{x:.0f}" cy="{y:.0f}" r="{r:.1f}" fill="{color}" '
                   f'opacity="{rnd.uniform(0.5, 1):.2f}"/>')
    return "".join(out)


def sun(x, y, r, color, rays=True):
    out = [f'<circle cx="{x}" cy="{y}" r="{r}" fill="{color}"/>']
    if rays:
        for i in range(12):
            a = i / 12 * 2 * math.pi
            x1, y1 = x + math.cos(a) * r * 1.3, y + math.sin(a) * r * 1.3
            x2, y2 = x + math.cos(a) * r * 1.65, y + math.sin(a) * r * 1.65
            out.append(f'<line x1="{x1:.0f}" y1="{y1:.0f}" x2="{x2:.0f}" y2="{y2:.0f}" '
                       f'stroke="{color}" stroke-width="{r * 0.16:.0f}" stroke-linecap="round"/>')
    return "".join(out)


def tree(x, base, h, trunk, crown, crown2=None):
    crown2 = crown2 or crown
    tw = h * 0.14
    return (f'<rect x="{x - tw / 2:.0f}" y="{base - h * 0.55:.0f}" width="{tw:.0f}" '
            f'height="{h * 0.6:.0f}" rx="{tw * 0.3:.0f}" fill="{trunk}"/>'
            f'<circle cx="{x:.0f}" cy="{base - h * 0.7:.0f}" r="{h * 0.3:.0f}" fill="{crown}"/>'
            f'<circle cx="{x - h * 0.25:.0f}" cy="{base - h * 0.55:.0f}" r="{h * 0.22:.0f}" fill="{crown2}"/>'
            f'<circle cx="{x + h * 0.25:.0f}" cy="{base - h * 0.58:.0f}" r="{h * 0.24:.0f}" fill="{crown2}"/>')


def balloon(x, y, r, color):
    return (f'<path d="M{x},{y + r * 1.15} q{-r * 0.3},{r * 0.8} {r * 0.1},{r * 1.6} '
            f't{-r * 0.2},{r * 1.4}" stroke="#44515E" stroke-width="3" fill="none"/>'
            f'<ellipse cx="{x}" cy="{y}" rx="{r}" ry="{r * 1.15}" fill="{color}"/>'
            f'<path d="M{x - 10},{y + r * 1.13} l10,14 l10,-14 Z" fill="{color}"/>'
            f'<ellipse cx="{x - r * 0.35}" cy="{y - r * 0.4}" rx="{r * 0.2}" ry="{r * 0.32}" '
            f'fill="#FFFFFF" opacity="0.45" transform="rotate(-25 {x - r * 0.35} {y - r * 0.4})"/>')


def honey_pot(x, base, s, pot, label, text_color):
    w, h = 170 * s, 190 * s
    top = base - h
    return (f'<path d="M{x - w * 0.42},{top + h * 0.14} C{x - w * 0.62},{top + h * 0.45} '
            f'{x - w * 0.6},{base - h * 0.05} {x - w * 0.3},{base} L{x + w * 0.3},{base} '
            f'C{x + w * 0.6},{base - h * 0.05} {x + w * 0.62},{top + h * 0.45} {x + w * 0.42},{top + h * 0.14} Z" '
            f'fill="{pot}"/>'
            f'<rect x="{x - w * 0.46:.0f}" y="{top:.0f}" width="{w * 0.92:.0f}" height="{h * 0.16:.0f}" '
            f'rx="{h * 0.06:.0f}" fill="{mix(pot, "#000000", 0.25)}"/>'
            f'<path d="M{x - w * 0.2},{top + h * 0.16} q0,{h * 0.22} {w * 0.07},{h * 0.22} '
            f'q{w * 0.07},0 {w * 0.07},{-h * 0.22} Z" fill="{mix(pot, "#FFD000", 0.5)}"/>'
            f'<rect x="{x - w * 0.34:.0f}" y="{top + h * 0.45:.0f}" width="{w * 0.68:.0f}" '
            f'height="{h * 0.26:.0f}" rx="8" fill="{label}"/>'
            f'<text x="{x:.0f}" y="{top + h * 0.64:.0f}" text-anchor="middle" '
            f'font-family="Noto Sans, sans-serif" font-weight="800" font-size="{h * 0.15:.0f}" '
            f'fill="{text_color}">HUNNY</text>')


def thistle(x, base, h, stem, flower):
    return (f'<path d="M{x},{base} C{x - 8},{base - h * 0.4} {x + 8},{base - h * 0.7} {x},{base - h}" '
            f'stroke="{stem}" stroke-width="7" fill="none" stroke-linecap="round"/>'
            f'<path d="M{x},{base - h * 0.45} q-45,-10 -60,-45 q30,5 60,25 Z" fill="{stem}"/>'
            f'<path d="M{x},{base - h * 0.65} q45,-10 60,-45 q-30,5 -60,25 Z" fill="{stem}"/>'
            f'<ellipse cx="{x}" cy="{base - h - 14}" rx="22" ry="26" fill="{mix(stem, "#FFFFFF", 0.15)}"/>'
            + "".join(f'<line x1="{x}" y1="{base - h - 30}" x2="{x + dx}" y2="{base - h - 72}" '
                      f'stroke="{flower}" stroke-width="7" stroke-linecap="round"/>'
                      for dx in (-26, -13, 0, 13, 26)))


def stick_house(x, base, s, color):
    sticks = []
    for i in range(9):
        t = i / 8
        sticks.append(f'<line x1="{x - 150 * s + t * 300 * s:.0f}" y1="{base}" '
                      f'x2="{x + (t - 0.5) * 40 * s:.0f}" y2="{base - 200 * s:.0f}" '
                      f'stroke="{color}" stroke-width="{9 * s:.0f}" stroke-linecap="round"/>')
    return "".join(sticks)


def rain(seed, color, n=160):
    rnd = random.Random(seed)
    return "".join(
        f'<line x1="{x:.0f}" y1="{y:.0f}" x2="{x - 10:.0f}" y2="{y + 34:.0f}" stroke="{color}" '
        f'stroke-width="3" stroke-linecap="round" opacity="0.45"/>'
        for x, y in ((rnd.uniform(0, W + 60), rnd.uniform(80, 900)) for _ in range(n)))


def acorn(x, y, s, nut, cap):
    return (f'<ellipse cx="{x}" cy="{y + 14 * s:.0f}" rx="{16 * s:.0f}" ry="{21 * s:.0f}" fill="{nut}"/>'
            f'<path d="M{x - 20 * s:.0f},{y + 2 * s:.0f} q{20 * s:.0f},{-26 * s:.0f} {40 * s:.0f},0 Z" fill="{cap}"/>'
            f'<line x1="{x}" y1="{y - 10 * s:.0f}" x2="{x + 4 * s:.0f}" y2="{y - 18 * s:.0f}" '
            f'stroke="{cap}" stroke-width="{4 * s:.0f}" stroke-linecap="round"/>')


def flower(x, y, r, petal, center):
    petals = "".join(f'<circle cx="{x + math.cos(a) * r:.0f}" cy="{y + math.sin(a) * r:.0f}" r="{r * 0.75:.0f}"/>'
                     for a in (i / 5 * 2 * math.pi - math.pi / 2 for i in range(5)))
    return f'<g fill="{petal}">{petals}</g><circle cx="{x}" cy="{y}" r="{r * 0.55:.0f}" fill="{center}"/>'


def carrot(x, base, s, orange, green):
    return (f'<path d="M{x - 18 * s:.0f},{base - 10 * s:.0f} L{x + 18 * s:.0f},{base - 10 * s:.0f} '
            f'L{x},{base + 55 * s:.0f} Z" fill="{orange}"/>'
            + "".join(f'<path d="M{x},{base - 8 * s:.0f} q{dx * s:.0f},{-40 * s:.0f} {dx * 1.6 * s:.0f},{-58 * s:.0f}" '
                      f'stroke="{green}" stroke-width="{7 * s:.0f}" fill="none" stroke-linecap="round"/>'
                      for dx in (-12, 0, 12)))


def fence(y, color):
    posts = "".join(f'<path d="M{x},{y} l0,-95 l14,-18 l14,18 l0,95 Z" fill="{color}"/>'
                    for x in range(0, W + 40, 52))
    return (posts + f'<rect x="0" y="{y - 75}" width="{W}" height="12" fill="{mix(color, "#000000", 0.12)}"/>'
            f'<rect x="0" y="{y - 35}" width="{W}" height="12" fill="{mix(color, "#000000", 0.12)}"/>')


def hop_trail(x0, y0, hops, length, height, color, width, dash):
    d = f"M{x0},{y0}"
    for _ in range(hops):
        d += f" q{length / 2},{-height} {length},0"
    return (f'<path d="{d}" stroke="{color}" stroke-width="{width}" fill="none" '
            f'stroke-dasharray="{dash}" stroke-linecap="round"/>')


def sign(x, y, text, board, ink, size=30):
    w = len(text) * size * 0.62 + 30
    return (f'<rect x="{x - 6}" y="{y}" width="12" height="130" fill="{mix(board, "#000000", 0.3)}"/>'
            f'<rect x="{x - w / 2:.0f}" y="{y - size * 0.4:.0f}" width="{w:.0f}" height="{size * 1.6:.0f}" '
            f'rx="6" fill="{board}" transform="rotate(-4 {x} {y})"/>'
            f'<text x="{x}" y="{y + size * 0.72:.0f}" text-anchor="middle" font-family="Noto Sans, sans-serif" '
            f'font-weight="700" font-size="{size}" fill="{ink}" transform="rotate(-4 {x} {y})">{text}</text>')


def scene_christopher_robin(a, c):
    return (cloud(420, 260, 1.1, "#FFFFFF") + cloud(1250, 190, 0.8, "#FFFFFF") + cloud(1600, 340, 1.0, "#FFFFFF")
            + sun(1650, 180, 70, a["detail"])
            + hill(760, 40, 1.2, 0.6, a["hill_far"])
            + tree(330, ground_y(760, 40, 1.2, 0.6, 330) + 40, 420, "#7A5234", "#4E8F45", "#5FA35A")
            + hill(870, 30, 1.6, 2.2, a["hill_near"])
            + balloon(1180, 430, 70, a["accent"])
            + "".join(flower(x, ground_y(870, 30, 1.6, 2.2, x) + 60, 11, a["detail"], "#FFFFFF")
                      for x in range(120, W, 190)))


def scene_winnie_the_pooh(a, c):
    return (stars(70, 1, a["detail"], 560)
            + f'<circle cx="1560" cy="230" r="110" fill="{a["detail"]}" opacity="0.95"/>'
            + hill(780, 35, 1.1, 1.0, a["hill_far"])
            + tree(1650, ground_y(780, 35, 1.1, 1.0, 1650) + 40, 460, "#4A3220", "#3E5A2A", "#34502A")
            + f'<ellipse cx="1560" cy="470" rx="42" ry="56" fill="{a["accent"]}"/>'
            + "".join(f'<circle cx="{1500 + i * 29}" cy="{430 + (i % 3) * 38}" r="5" fill="{a["detail"]}"/>'
                      for i in range(5))
            + hill(900, 25, 1.4, 2.6, a["hill_near"])
            + honey_pot(470, 930, 1.35, a["accent"], a["detail"], "#3D2410")
            + honey_pot(760, 950, 1.0, mix(a["accent"], "#E8834A", 0.4), a["detail"], "#3D2410")
            + honey_pot(990, 965, 0.8, a["accent"], a["detail"], "#3D2410"))


def scene_eeyore(a, c):
    base = 880
    return (cloud(300, 180, 1.4, "#7C84A6", 0.8) + cloud(900, 140, 1.2, "#6D7596", 0.8)
            + cloud(1500, 200, 1.5, "#7C84A6", 0.8)
            + rain(3, "#C9CFEA")
            + hill(800, 30, 1.0, 0.3, a["hill_far"])
            + stick_house(1420, ground_y(880, 20, 1.3, 1.8, 1420) + 10, 1.2, "#8A7A66")
            + hill(base, 20, 1.3, 1.8, a["hill_near"])
            + "".join(thistle(x, ground_y(base, 20, 1.3, 1.8, x) + 40, h, "#5E7A5E", a["accent"])
                      for x, h in ((180, 170), (330, 230), (520, 150), (760, 200), (1000, 160), (1780, 210)))
            + f'<path d="M1180,905 q-30,-35 -55,-5 q25,25 55,5 q30,-35 55,-5 q-25,25 -55,5 Z" fill="{a["detail"]}"/>'
            + f'<circle cx="1180" cy="905" r="10" fill="{a["detail"]}"/>')


def scene_piglet(a, c):
    trunk_x, base = 1250, 880
    return (sun(330, 200, 60, "#FFE08A")
            + cloud(760, 240, 0.9, "#FFFFFF") + cloud(1550, 170, 0.7, "#FFFFFF")
            + hill(780, 30, 1.2, 1.4, a["hill_far"])
            + f'<rect x="{trunk_x - 110}" y="330" width="220" height="580" rx="40" fill="{a["accent"]}"/>'
            + f'<circle cx="{trunk_x}" cy="300" r="260" fill="#6FAE66"/>'
            + f'<circle cx="{trunk_x - 220}" cy="380" r="170" fill="#83BF78"/>'
            + f'<circle cx="{trunk_x + 220}" cy="360" r="180" fill="#83BF78"/>'
            + f'<rect x="{trunk_x - 55}" y="690" width="110" height="170" rx="55" fill="{mix(a["accent"], "#000000", 0.35)}"/>'
            + f'<circle cx="{trunk_x + 30}" cy="780" r="9" fill="#FFD23F"/>'
            + sign(trunk_x + 330, 740, "TRESPASSERS W", "#F4E3C1", "#5A3A22")
            + hill(base, 20, 1.5, 0.4, a["hill_near"])
            + "".join(acorn(x, ground_y(base, 20, 1.5, 0.4, x) + 70, 1.2, "#B8864E", "#7A5234")
                      for x in (220, 420, 640, 1700))
            + "".join(flower(x, ground_y(base, 20, 1.5, 0.4, x) + 130, 12, a["detail"], "#FFE08A")
                      for x in range(90, W, 150)))


def scene_tigger(a, c):
    stripes = "".join(
        f'<path d="M-100,{y} C400,{y - 120} 800,{y + 140} 1200,{y} S1800,{y - 80} 2100,{y + 30}" '
        f'stroke="{a["accent"]}" stroke-width="70" fill="none" opacity="{op}" stroke-linecap="round"/>'
        for y, op in ((260, 0.35), (470, 0.45), (680, 0.35)))
    return (stars(60, 5, a["detail"], 900)
            + stripes
            + hop_trail(80, 930, 5, 360, 520, a["detail"], 9, "2 26")
            + hop_trail(260, 980, 7, 240, 260, a["accent"], 7, "2 22")
            + "".join(f'<path d="M{x},{y} l14,34 l38,4 l-28,24 l9,37 l-33,-20 l-33,20 l9,-37 l-28,-24 l38,-4 Z" '
                      f'fill="{a["detail"]}"/>'
                      for x, y in ((440, 360), (1160, 330), (1700, 420)))
            + hill(990, 22, 1.3, 0.9, a["accent"])
            + "".join(f'<path d="M{x},{ground_y(990, 22, 1.3, 0.9, x) + 6:.0f} q30,40 10,90" '
                      f'stroke="{a["hill_near"]}" stroke-width="22" fill="none" stroke-linecap="round"/>'
                      for x in range(60, W, 170)))


def scene_kanga_and_roo(a, c):
    base = 860
    prints = "".join(f'<ellipse cx="{x}" cy="{ground_y(base, 25, 1.2, 2.0, x) + 90}" rx="16" ry="9" '
                     f'fill="{mix(a["hill_near"], "#000000", 0.25)}"/>'
                     for x in range(260, 1700, 200))
    return (sun(1620, 190, 75, "#FFD36B")
            + cloud(380, 230, 0.9, "#FFFFFF") + cloud(980, 170, 0.7, "#FFFFFF")
            + hill(740, 35, 1.0, 0.8, a["hill_far"])
            + tree(1760, ground_y(740, 35, 1.0, 0.8, 1760) + 60, 380, "#7A5234", "#6E9E5A", "#7FAF66")
            + hill(base, 25, 1.2, 2.0, a["hill_near"])
            + hop_trail(160, 800, 4, 400, 420, a["accent"], 10, "3 28")
            + hop_trail(260, 830, 8, 200, 180, a["detail"], 8, "3 20")
            + prints
            + "".join(flower(x, ground_y(base, 25, 1.2, 2.0, x) + 150, 12, "#F7A8C4", "#FFE08A")
                      for x in range(120, W, 240)))


def scene_rabbit(a, c):
    rows = "".join(f'<rect x="0" y="{y}" width="{W}" height="34" rx="17" fill="{mix(a["hill_near"], "#000000", 0.18)}"/>'
                   for y in (840, 930, 1020))
    carrots = "".join(carrot(x + (y // 90 % 2) * 60, y + 8, 1.0, a["accent"], a["detail"])
                      for y in (840, 930, 1020) for x in range(70, W, 150))
    return (sun(260, 180, 65, "#FFD84D")
            + cloud(900, 200, 0.9, "#FFFFFF") + cloud(1500, 260, 1.1, "#FFFFFF")
            + hill(640, 30, 1.0, 1.2, a["hill_far"])
            + fence(760, "#FFF8EC")
            + f'<rect x="0" y="780" width="{W}" height="300" fill="{a["hill_near"]}"/>'
            + rows + carrots)


def scene_owl(a, c):
    branch_y = 560
    return (stars(140, 8, a["detail"], 760)
            + f'<circle cx="480" cy="270" r="150" fill="{a["detail"]}"/>'
            + f'<circle cx="440" cy="240" r="24" fill="{mix(a["detail"], "#000000", 0.08)}"/>'
            + f'<circle cx="530" cy="320" r="16" fill="{mix(a["detail"], "#000000", 0.08)}"/>'
            + hill(850, 25, 1.1, 0.5, a["hill_far"])
            + f'<path d="M1330,1080 C1350,800 1300,500 1370,-20 L1610,-20 C1640,500 1600,800 1640,1080 Z" '
              f'fill="#1F160E"/>'
            + f'<path d="M1390,{branch_y} C1200,{branch_y - 20} 1000,{branch_y + 10} 820,{branch_y - 30}" '
              f'stroke="#1F160E" stroke-width="34" fill="none" stroke-linecap="round"/>'
            + f'<rect x="1440" y="300" width="96" height="120" rx="48" fill="{a["accent"]}"/>'
            + f'<line x1="1488" y1="300" x2="1488" y2="420" stroke="#1F160E" stroke-width="7"/>'
            + f'<line x1="1440" y1="362" x2="1536" y2="362" stroke="#1F160E" stroke-width="7"/>'
            + f'<ellipse cx="1060" cy="{branch_y - 80}" rx="62" ry="78" fill="#6B5238"/>'
            + f'<path d="M1010,{branch_y - 140} l14,-34 l18,30 Z M1110,{branch_y - 140} l-14,-34 l-18,30 Z" fill="#6B5238"/>'
            + f'<ellipse cx="1060" cy="{branch_y - 55}" rx="38" ry="44" fill="{mix("#6B5238", "#FFFFFF", 0.25)}"/>'
            + "".join(f'<circle cx="{1060 + dx}" cy="{branch_y - 112}" r="22" fill="{a["detail"]}"/>'
                      f'<circle cx="{1060 + dx}" cy="{branch_y - 112}" r="10" fill="#1F160E"/>'
                      for dx in (-24, 24))
            + f'<path d="M1052,{branch_y - 96} l8,16 l8,-16 Z" fill="{a["accent"]}"/>'
            + hill(960, 20, 1.5, 1.7, a["hill_near"]))


SCENES = {
    "christopher-robin": scene_christopher_robin,
    "winnie-the-pooh": scene_winnie_the_pooh,
    "eeyore": scene_eeyore,
    "piglet": scene_piglet,
    "tigger": scene_tigger,
    "kanga-and-roo": scene_kanga_and_roo,
    "rabbit": scene_rabbit,
    "owl": scene_owl,
}


def wallpaper_svg(theme):
    a = theme["art"]
    body = SCENES[theme["id"]](a, theme["colors"])
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}" preserveAspectRatio="xMidYMid slice">
<!-- Generated by scripts/gen-themes.py from themes/{theme['id']}.toml -->
<defs><linearGradient id="sky" x1="0" y1="0" x2="0" y2="1">
<stop offset="0" stop-color="{a['sky_top']}"/><stop offset="1" stop-color="{a['sky_bottom']}"/>
</linearGradient></defs>
<rect width="{W}" height="{H}" fill="url(#sky)"/>
{body}
</svg>
"""


# --- driver --------------------------------------------------------------------

def load_themes():
    themes = []
    for path in sorted((ROOT / "themes").glob("*.toml")):
        theme = tomllib.loads(path.read_text())
        theme["id"] = path.stem
        themes.append(theme)
    return themes


def install_current(out, theme_id):
    """What `lighthouse-theme set` does, applied to the rootfs tree."""
    src = out / "usr/share/lighthouse/themes" / theme_id
    current = out / "etc/lighthouse/theme"
    current.mkdir(parents=True, exist_ok=True)
    for name in ("theme.json", "palette.json", "niri.kdl"):
        shutil.copy(src / name, current / name)
    shutil.copy(src / "noctalia.toml", out / "etc/lighthouse/noctalia/theme.toml")


def generate(out):
    problems = []
    for theme in load_themes():
        if theme["id"] not in SCENES:
            problems.append(f"{theme['id']}: no wallpaper scene")
            continue
        problems += [f"{theme['id']}: {p}" for p in contrast_problems(theme)]
        d = out / "usr/share/lighthouse/themes" / theme["id"]
        d.mkdir(parents=True, exist_ok=True)
        palette = json.dumps(noctalia_palette(theme), indent=2) + "\n"
        (d / "palette.json").write_text(palette)
        (d / "theme.json").write_text(json.dumps(theme_json(theme), indent=2) + "\n")
        (d / "niri.kdl").write_text(niri_kdl(theme))
        (d / "noctalia.toml").write_text(noctalia_toml(theme))
        (d / "wallpaper.svg").write_text(wallpaper_svg(theme))
        palettes = out / "etc/lighthouse/noctalia/palettes"
        palettes.mkdir(parents=True, exist_ok=True)
        (palettes / f"{theme['id']}.json").write_text(palette)
    install_current(out, DEFAULT_THEME)
    return problems


GENERATED = ["usr/share/lighthouse/themes", "etc/lighthouse/noctalia/palettes",
             "etc/lighthouse/theme", "etc/lighthouse/noctalia/theme.toml"]


def main():
    check = "--check" in sys.argv
    rootfs = ROOT / "rootfs"
    if check:
        with tempfile.TemporaryDirectory() as tmp:
            problems = generate(Path(tmp))
            for rel in GENERATED:
                a, b = Path(tmp) / rel, rootfs / rel
                files_a = sorted(p.relative_to(a) for p in a.rglob("*") if p.is_file()) if a.is_dir() else None
                files_b = sorted(p.relative_to(b) for p in b.rglob("*") if p.is_file()) if b.is_dir() else None
                same = (files_a == files_b and all((a / f).read_bytes() == (b / f).read_bytes() for f in files_a)
                        if a.is_dir() else b.is_file() and a.read_bytes() == b.read_bytes())
                if not same:
                    problems.append(f"rootfs/{rel} is stale; run scripts/gen-themes.py")
    else:
        problems = generate(rootfs)

    for theme in load_themes():
        c = theme["colors"]
        print(f"{theme['id']:<20} {theme['mode']:<5}  text {contrast(c['on_surface'], c['surface']):5.2f}  "
              f"primary {contrast(c['primary'], c['surface']):4.2f}  "
              f"on-primary {contrast(c['on_primary'], c['primary']):4.2f}")
    if problems:
        print("\n".join(["", "Problems:"] + [f"  {p}" for p in problems]))
        sys.exit(1)


if __name__ == "__main__":
    main()
